import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Copy, Lock, Loader2, Activity } from "lucide-react"
import { useToast } from "@/hooks/use-toast"
import { TeamLogo } from "./TeamLogo"
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useState } from "react"

interface ParlayCardProps {
    legs: any[]
    totalOdds: string
    confidence: number
    riskLevel: number
}

import { useNotification } from "@/contexts/NotificationContext"

export function ParlayCard({ legs, totalOdds, confidence, riskLevel }: ParlayCardProps) {
    const { toast } = useToast()
    const { triggerNewBetNotification } = useNotification()
    const [open, setOpen] = useState(false)
    const [stake, setStake] = useState("10")
    const [sportsbook, setSportsbook] = useState("FanDuel")
    const [loading, setLoading] = useState(false)
    const [copied, setCopied] = useState(false)

    const handleCopy = () => {
        const calculatePayout = (oddsStr: string, wager: number) => {
            const odds = parseInt(oddsStr);
            if (isNaN(odds)) return "0.00";
            if (odds > 0) return (wager + (wager * odds / 100)).toFixed(2);
            return (wager + (wager * 100 / Math.abs(odds))).toFixed(2);
        }

        const text = `🎯 ProfitPicks AI - ${totalOdds} Parlay\n\n` +
            legs.map((l: any) => {
                const line = l.line || '';
                return `🏀 ${l.team} ${line} (${l.odds}) vs ${l.opponent}`
            }).join('\n') +
            `\n\nTotal Odds: ${totalOdds}\n$10 bet → $${calculatePayout(totalOdds, 10)} payout\n\nGenerated by ProfitPicks AI\nprofitpicksai.com`

        navigator.clipboard.writeText(text)
        setCopied(true)
        toast({ title: "Copied to clipboard!", description: "Paste it into your sportsbook." })
        setTimeout(() => setCopied(false), 2000)
    }

    const handleLockIn = async () => {
        setLoading(true)
        try {
            const response = await fetch('/api/track-bet', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    stake: parseFloat(stake),
                    sportsbook,
                    legs,
                    totalOdds,
                    confidence,
                    riskLevel
                })
            })

            if (!response.ok) {
                const data = await response.json()
                throw new Error(data.error || 'Failed to track')
            }

            toast({ title: "Bet Locked In! 🔒", description: "Added to your Bet History." })
            triggerNewBetNotification()
            setOpen(false)
        } catch (error) {
            toast({
                variant: "destructive",
                title: "Error",
                description: error instanceof Error ? error.message : "Failed to lock in bet."
            })
        } finally {
            setLoading(false)
        }
    }

    // Determine badge color based on confidence
    const confidenceColor = confidence >= 75 ? "bg-emerald text-emerald-foreground border-emerald/50" :
        confidence >= 60 ? "bg-yellow-500/20 text-yellow-500 border-yellow-500/50" :
            "bg-red-500/20 text-red-500 border-red-500/50";

    return (
        <Card className="w-full bg-gradient-to-b from-zinc-900 to-black border-zinc-800 shadow-2xl relative overflow-hidden group/card">
            {/* Top Glow Border */}
            <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-emerald-600 via-emerald-400 to-emerald-600 opacity-80" />

            <div className="absolute top-4 right-4 z-10">
                <Badge variant="outline" className={`${confidenceColor} backdrop-blur-md shadow-[0_0_15px_-3px_rgba(16,185,129,0.3)] px-3 py-1 flex items-center gap-1.5`}>
                    <Activity className="w-3.5 h-3.5" />
                    {confidence}% Confidence
                </Badge>
            </div>

            <CardHeader className="pb-2 pt-6">
                <CardTitle className="flex items-center gap-2">
                    <span className="bg-emerald/10 p-2 rounded-lg ring-1 ring-emerald/20">
                        <Activity className="w-5 h-5 text-emerald" />
                    </span>
                    <span className="text-xl font-black tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-white to-white/70">
                        AI PARLAY
                    </span>
                </CardTitle>
                <CardDescription className="flex items-center gap-2 text-base font-medium text-emerald/90">
                    <span className="font-bold text-white">{legs.length} Legs</span>
                    <span className="w-1 h-1 bg-white/30 rounded-full" />
                    <span className="font-mono text-emerald-400 font-bold">{totalOdds} Odds</span>
                </CardDescription>
            </CardHeader>

            <CardContent className="space-y-3 relative z-10 px-4">
                {legs.map((leg: any, i: number) => {
                    const isProp = leg.player && leg.player.length > 0;
                    const headerText = isProp ? leg.player : leg.team;
                    const subText = isProp ? `${leg.team} vs ${leg.opponent}` : `vs ${leg.opponent}`;
                    const items = [leg.team, leg.opponent];

                    return (
                        <div key={i} className="group flex flex-col gap-2 p-3.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/5 hover:border-emerald/30 transition-all duration-300 shadow-lg hover:shadow-[0_0_15px_-5px_rgba(16,185,129,0.1)]">
                            <div className="flex justify-between items-start">
                                <div className="flex items-center gap-3">
                                    <div className="relative w-10 h-10 bg-white/5 rounded-full ring-1 ring-white/10 group-hover:ring-emerald/40 transition-colors flex items-center justify-center shrink-0 overflow-hidden">
                                        <TeamLogo name={leg.team} className="w-7 h-7" />
                                    </div>
                                    <div className="flex flex-col">
                                        <span className="text-sm font-bold text-white group-hover:text-emerald-300 transition-colors leading-tight">
                                            {headerText}
                                        </span>
                                        <span className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold">
                                            {leg.bet_type} • {subText}
                                        </span>
                                    </div>
                                </div>
                                <div className="flex flex-col items-end gap-1">
                                    <Badge variant="secondary" className="font-mono text-xs bg-black/40 text-emerald-400 border border-emerald/20 px-2 py-0.5">
                                        {leg.odds}
                                    </Badge>
                                    {leg.sportsbook && (
                                        <span className="text-[9px] text-muted-foreground/60 uppercase tracking-wider font-bold">
                                            via {leg.sportsbook}
                                        </span>
                                    )}
                                </div>
                            </div>

                            <div className="mt-1 pl-[3.25rem]">
                                <div className="flex items-baseline gap-2">
                                    <span className="text-sm font-black text-white/90">
                                        {leg.line === 'Yes' ? 'To Score' : leg.line}
                                    </span>
                                </div>
                                <p className="text-[10px] text-muted-foreground/80 italic mt-1.5 leading-relaxed bg-black/20 p-2 rounded-lg border border-white/5 whitespace-normal break-words">
                                    "{leg.reasoning}"
                                </p>
                            </div>
                        </div>
                    )
                })}
            </CardContent>

            <CardFooter className="flex flex-col gap-4 pt-6 pb-8 px-6 bg-gradient-to-t from-emerald-950/20 to-transparent border-t border-white/5 relative z-20">
                <div className="flex w-full gap-4">
                    <Button
                        onClick={handleCopy}
                        variant="outline"
                        className="flex-1 border-white/10 bg-white/5 hover:bg-white/10 hover:text-white hover:border-white/20 transition-all text-xs h-12 uppercase tracking-widest font-bold backdrop-blur-sm"
                    >
                        {copied ? (
                            <span className="text-emerald-400 flex items-center gap-2 animate-in fade-in zoom-in duration-300">
                                Copied <span className="text-lg">✓</span>
                            </span>
                        ) : (
                            <span className="flex items-center gap-2 opacity-70 group-hover:opacity-100 transition-opacity">
                                <Copy className="h-3.5 w-3.5" /> Copy Link
                            </span>
                        )}
                    </Button>

                    <Dialog open={open} onOpenChange={setOpen}>
                        <DialogTrigger asChild>
                            <Button className="flex-[1.8] relative overflow-hidden bg-gradient-to-r from-emerald-600 to-emerald-400 text-white border-0 shadow-[0_0_40px_-10px_rgba(16,185,129,0.5)] hover:shadow-[0_0_60px_-15px_rgba(16,185,129,0.7)] transition-all duration-500 transform hover:-translate-y-1 hover:scale-[1.02] text-sm h-12 uppercase tracking-widest font-black group">
                                <div className="absolute inset-0 bg-white/20 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000 transform skew-x-12" />
                                <span className="relative z-10 flex items-center gap-2">
                                    <Lock className="h-4 w-4 transition-transform group-hover:scale-110" />
                                    Lock In Parlay
                                </span>
                            </Button>
                        </DialogTrigger>
                        <DialogContent className="sm:max-w-[425px]">
                            <DialogHeader>
                                <DialogTitle>Lock In Bet</DialogTitle>
                                <DialogDescription>
                                    Track this bet to calculating your winnings and hit rate.
                                </DialogDescription>
                            </DialogHeader>
                            <div className="grid gap-4 py-4">
                                <div className="grid grid-cols-4 items-center gap-4">
                                    <Label htmlFor="sportsbook" className="text-right">
                                        Book
                                    </Label>
                                    <Select value={sportsbook} onValueChange={setSportsbook}>
                                        <SelectTrigger className="col-span-3">
                                            <SelectValue placeholder="Select sportsbook" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="FanDuel">FanDuel</SelectItem>
                                            <SelectItem value="DraftKings">DraftKings</SelectItem>
                                            <SelectItem value="BetMGM">BetMGM</SelectItem>
                                            <SelectItem value="Caesars">Caesars</SelectItem>
                                            <SelectItem value="Other">Other</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div className="grid grid-cols-4 items-center gap-4">
                                    <Label htmlFor="stake" className="text-right">
                                        Wager ($)
                                    </Label>
                                    <Input
                                        id="stake"
                                        type="number"
                                        value={stake}
                                        onChange={(e) => setStake(e.target.value)}
                                        className="col-span-3"
                                    />
                                </div>
                            </div>
                            <DialogFooter>
                                <Button type="submit" onClick={handleLockIn} disabled={loading} className="bg-emerald text-white">
                                    {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                                    Confirm Lock
                                </Button>
                            </DialogFooter>
                        </DialogContent>
                    </Dialog>
                </div>
                <p className="text-[10px] text-center text-muted-foreground/40 font-mono uppercase tracking-widest">
                    Track & Analyze Your Performance
                </p>
            </CardFooter>
        </Card >
    )
}
