import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Copy, Lock, Loader2, Activity, ChevronRight } from "lucide-react"
import { useToast } from "@/hooks/use-toast"
import { TeamLogo } from "./TeamLogo"
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { useState } from "react"

interface ParlayCardProps {
    legs: any[]
    totalOdds: string
    confidence: number
    riskLevel: number
    strategy?: string
}

import { useNotification } from "@/contexts/NotificationContext"

export function ParlayCard({ legs, totalOdds, confidence, riskLevel, strategy }: ParlayCardProps) {
    const { toast } = useToast()
    const { triggerNewBetNotification } = useNotification()
    const [open, setOpen] = useState(false)
    const [stake, setStake] = useState("10")
    const [sportsbook, setSportsbook] = useState("FanDuel")
    const [loading, setLoading] = useState(false)
    const [copied, setCopied] = useState(false)

    const handleCopy = () => {
        const calculatePayout = (oddsStr: string, wager: number) => {
            const odds = parseInt(oddsStr);
            if (isNaN(odds)) return "0.00";
            if (odds > 0) return (wager + (wager * odds / 100)).toFixed(2);
            return (wager + (wager * 100 / Math.abs(odds))).toFixed(2);
        }

        const text = `🎯 ProfitPicks AI - ${totalOdds} Parlay\n\n` +
            (strategy ? `Strategy: ${strategy}\n\n` : '') +
            legs.map((l: any) => {
                const line = l.line || '';
                const prop = l.prop_market ? ` ${l.prop_market}` : '';
                return `🏀 ${l.player || l.team}${prop} ${line} (${l.odds}) vs ${l.opponent}`
            }).join('\n') +
            `\n\nTotal Odds: ${totalOdds}\n$10 bet → $${calculatePayout(totalOdds, 10)} payout\n\nGenerated by ProfitPicks AI\nprofitpicksai.com`

        navigator.clipboard.writeText(text)
        setCopied(true)
        toast({ title: "Copied to clipboard!", description: "Paste it into your sportsbook." })
        setTimeout(() => setCopied(false), 2000)
    }

    const handleLockIn = async () => {
        setLoading(true)
        try {
            const response = await fetch('/api/track-bet', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    stake: parseFloat(stake),
                    sportsbook,
                    legs,
                    totalOdds,
                    confidence,
                    riskLevel
                })
            })

            if (!response.ok) {
                const data = await response.json()
                throw new Error(data.error || 'Failed to track')
            }

            toast({ title: "Bet Locked In! 🔒", description: "Added to your Bet History." })
            triggerNewBetNotification()
            setOpen(false)
        } catch (error) {
            toast({
                variant: "destructive",
                title: "Error",
                description: error instanceof Error ? error.message : "Failed to lock in bet."
            })
        } finally {
            setLoading(false)
        }
    }

    // Determine badge color based on confidence
    const confidenceColor = confidence >= 70 ? "bg-emerald text-emerald-foreground border-emerald/50" :
        confidence >= 40 ? "bg-yellow-500/20 text-yellow-500 border-yellow-500/50" :
            confidence >= 20 ? "bg-orange-500/20 text-orange-400 border-orange-500/50" :
                "bg-red-500/20 text-red-500 border-red-500/50";

    return (
        <Card className="w-full bg-gradient-to-b from-zinc-900 to-black border-zinc-800 shadow-2xl relative overflow-hidden group/card">
            {/* Top Glow Border */}
            <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-emerald-600 via-emerald-400 to-emerald-600 opacity-80" />

            <div className="absolute top-3 right-3 z-10">
                <Badge variant="outline" className={`${confidenceColor} backdrop-blur-md border-emerald-500/20 shadow-[0_0_20px_-5px_rgba(16,185,129,0.4)] px-2.5 py-0.5 flex items-center gap-1.5 text-[10px] font-black uppercase tracking-tighter`}>
                    <Activity className="w-3 h-3 animate-pulse" />
                    {confidence >= 70 ? 'SHARP EDGE' : confidence >= 40 ? 'SOLID VALUE' : confidence >= 20 ? 'HIGH RISK PLAY' : 'MOONSHOT'}
                </Badge>
            </div>

            <CardHeader className="flex flex-col space-y-0.5 pb-2 pt-3 px-4 relative z-20 border-b border-white/5">
                <CardTitle className="text-sm font-black text-white tracking-widest uppercase flex items-center justify-between">
                    <span className="flex items-center gap-2">
                        <Activity className="w-3 h-3 text-emerald-400" /> AI PARLAY
                    </span>
                </CardTitle>
                <CardDescription className="flex items-center gap-2 text-[9px] font-bold text-emerald/70 leading-none">
                    <span className="text-white/80">{legs.length} LEGS</span>
                    <span className="w-1 h-1 bg-white/20 rounded-full" />
                    <span className="text-emerald-400 font-black">{totalOdds}</span>
                </CardDescription>
            </CardHeader>

            {strategy && (
                <div className="px-4 py-2 bg-emerald-500/5 border-b border-emerald-500/10">
                    <p className="text-[10px] text-emerald-400/90 font-bold italic leading-relaxed">
                        <span className="text-white not-italic font-black mr-1 uppercase text-[8px] tracking-widest">Logic:</span>
                        "{strategy}"
                    </p>
                </div>
            )}

            <CardContent className="space-y-1 relative z-10 px-2 py-1 flex-1 overflow-hidden pt-2">
                {legs.map((leg: any, i: number) => {
                    const isProp = leg.player && leg.player.length > 0;
                    const subText = isProp ? `${leg.team} vs ${leg.opponent}` : `vs ${leg.opponent}`;

                    return (
                        <div key={i} className="group relative flex flex-col gap-1 py-1.5 px-2 rounded-xl border border-white/[0.03] bg-zinc-900/40 hover:bg-emerald-500/[0.04] transition-all duration-300">
                            <div className="relative z-10 flex justify-between items-center gap-2">
                                <div className="flex gap-2 items-center min-w-0">
                                    <div className="relative w-6 h-6 flex items-center justify-center shrink-0">
                                        <div className="absolute inset-0 bg-white/5 rounded-full blur-[1px]" />
                                        <div className="relative w-full h-full rounded-full bg-zinc-950 border border-white/10 flex items-center justify-center overflow-hidden">
                                            <TeamLogo name={leg.team} className="w-3.5 h-3.5 relative z-10" />
                                        </div>
                                    </div>

                                    <div className="flex flex-col min-w-0">
                                        <div className="flex items-center gap-1.5">
                                            <span className="text-[11px] font-black text-white tracking-tight truncate">
                                                {leg.player || leg.team}
                                            </span>
                                            {isProp && (
                                                <Badge className="bg-emerald-500/10 text-emerald-400 border-none text-[7px] h-3 px-1 font-black leading-none">
                                                    PROP
                                                </Badge>
                                            )}
                                        </div>
                                        <p className="text-[8px] font-bold text-zinc-500 truncate uppercase mt-[-1px]">
                                            {isProp && leg.prop_market ? (
                                                <>
                                                    <span className="text-emerald-500/80">{leg.prop_market}</span>
                                                    {' '}
                                                    <span className="text-zinc-700 italic lowercase font-medium">({leg.team.toLowerCase()} vs {leg.opponent.toLowerCase()})</span>
                                                </>
                                            ) : (
                                                <>
                                                    {leg.bet_type === 'moneyline' ? 'MONEYLINE' : leg.bet_type === 'spread' ? 'SPREAD' : leg.bet_type === 'totals' ? 'GAME TOTAL' : leg.bet_type.replace('_', ' ')}
                                                    {' '}
                                                    <span className="text-zinc-700 italic lowercase font-medium">(vs {leg.opponent.toLowerCase()})</span>
                                                </>
                                            )}
                                        </p>
                                    </div>
                                </div>

                                <div className="flex flex-col items-end shrink-0">
                                    <div className="flex items-center gap-1.5">
                                        <span className="text-[10px] font-black text-white tracking-tighter">
                                            {leg.line === 'Yes' ? 'WIN' : leg.line}
                                        </span>
                                        <Badge variant="outline" className="text-[10px] font-mono font-black h-4 px-1.5 border-emerald-500/20 text-emerald-400 bg-emerald-500/5">
                                            {leg.odds}
                                        </Badge>
                                    </div>
                                    <span className="text-[7px] font-black text-zinc-600 uppercase tracking-tighter">
                                        {leg.sportsbook}
                                    </span>
                                </div>
                            </div>

                            <div className="relative z-10 bg-black/30 py-1.5 px-2 rounded-lg border border-white/[0.02]">
                                <p className="text-[9px] leading-[1.25] text-zinc-400 group-hover:text-zinc-200 transition-colors font-medium">
                                    {leg.reasoning}
                                </p>
                            </div>
                        </div>
                    )
                })}
            </CardContent>

            <CardFooter className="flex flex-col gap-2 pt-1.5 pb-2 px-2.5 bg-gradient-to-t from-emerald-950/20 to-transparent border-t border-white/5 relative z-20 shrink-0">
                <div className="flex w-full gap-2">
                    <Button
                        onClick={handleCopy}
                        variant="outline"
                        className="flex-1 border-white/10 bg-white/5 hover:bg-white/10 hover:text-white transition-all text-[8px] h-7 uppercase tracking-widest font-bold"
                    >
                        {copied ? 'COPIED ✓' : 'COPY'}
                    </Button>

                    <Dialog open={open} onOpenChange={setOpen}>
                        <DialogTrigger asChild>
                            <Button className="flex-[2] relative overflow-hidden bg-gradient-to-r from-emerald-600 to-emerald-400 text-white border-0 shadow-lg text-[10px] h-8 uppercase tracking-widest font-black group">
                                <span className="relative z-10 flex items-center gap-1.5">
                                    <Lock className="w-3 h-3" /> LOCK IN
                                </span>
                            </Button>
                        </DialogTrigger>
                        <DialogContent className="sm:max-w-[425px]">
                            <DialogHeader>
                                <DialogTitle>Lock In Bet</DialogTitle>
                                <DialogDescription>
                                    Track this bet to calculating your winnings and hit rate.
                                </DialogDescription>
                            </DialogHeader>
                            <div className="grid gap-4 py-4">
                                <div className="grid grid-cols-1 sm:grid-cols-4 items-center gap-2 sm:gap-4">
                                    <Label htmlFor="sportsbook" className="text-left sm:text-right">
                                        Book
                                    </Label>
                                    <Select value={sportsbook} onValueChange={setSportsbook}>
                                        <SelectTrigger className="col-span-1 sm:col-span-3">
                                            <SelectValue placeholder="Select sportsbook" />
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="FanDuel">FanDuel</SelectItem>
                                            <SelectItem value="DraftKings">DraftKings</SelectItem>
                                            <SelectItem value="BetMGM">BetMGM</SelectItem>
                                            <SelectItem value="Caesars">Caesars</SelectItem>
                                            <SelectItem value="Other">Other</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </div>
                                <div className="grid grid-cols-1 sm:grid-cols-4 items-center gap-2 sm:gap-4">
                                    <Label htmlFor="stake" className="text-left sm:text-right">
                                        Wager ($)
                                    </Label>
                                    <Input
                                        id="stake"
                                        type="number"
                                        value={stake}
                                        onChange={(e) => setStake(e.target.value)}
                                        className="col-span-1 sm:col-span-3"
                                    />
                                </div>
                            </div>
                            <DialogFooter>
                                <Button type="submit" onClick={handleLockIn} disabled={loading} className="bg-emerald text-white">
                                    {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                                    Confirm Lock
                                </Button>
                            </DialogFooter>
                        </DialogContent>
                    </Dialog>
                </div>
                <p className="text-[10px] text-center text-muted-foreground/40 font-mono uppercase tracking-widest">
                    Track & Analyze Your Performance
                </p>
            </CardFooter>
        </Card >
    )
}
