import { LegalPageLayout } from "@/components/landing/LegalPageLayout"
import { ScrollText, LineChart, AlertCircle, Copyright, Scale } from "lucide-react"

export default function TermsPage() {
    return (
        <LegalPageLayout
            title="Terms of Service"
            subtitle="Last updated: March 17, 2026"
        >
            <section className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8">
                <div className="flex items-center gap-3 mb-6">
                    <ScrollText className="w-6 h-6 text-emerald-500" />
                    <h2 className="text-xl md:text-2xl font-black text-white tracking-tight uppercase italic">1. Acceptance of Terms</h2>
                </div>
                <p className="text-zinc-400 leading-relaxed font-medium">
                    By accessing and using Sharp Picks AI (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service. Our platform provides elite sports analytics and data processing for entertainment and informational purposes only.
                </p>
            </section>

            <section className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8">
                <div className="flex items-center gap-3 mb-6">
                    <LineChart className="w-6 h-6 text-blue-500" />
                    <h2 className="text-xl md:text-2xl font-black text-white tracking-tight uppercase italic">2. Description of Service</h2>
                </div>
                <p className="text-zinc-400 leading-relaxed font-medium">
                    Sharp Picks AI provides advanced sports data analytics, predictive modeling, and +EV (Expected Value) identification using proprietary, high-speed AI algorithms. <strong className="text-white border-b border-blue-500/30 pb-0.5">We do not facilitate sports wagering, nor are we a licensed gambling operator.</strong> We are a data intelligence suite.
                </p>
            </section>

            <section className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8">
                <div className="flex items-center gap-3 mb-6">
                    <AlertCircle className="w-6 h-6 text-yellow-500" />
                    <h2 className="text-xl md:text-2xl font-black text-white tracking-tight uppercase italic">3. Use for Entertainment Only</h2>
                </div>
                <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-xl p-4 mb-6">
                    <p className="text-zinc-300 leading-relaxed font-medium">
                        <strong className="text-yellow-400 font-bold uppercase tracking-wider mr-2">IMPORTANT:</strong> 
                        All data, predictions, and "picks" generated by Sharp Picks AI are for entertainment purposes only. Sports betting involves extreme variance and significant risk. Sharp Picks AI does not guarantee any financial outcome and is not responsible for any losses incurred as a result of deploying our analytical tools.
                    </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {[
                        "Past performance does not guarantee future results.",
                        "The user assumes total risk for any betting activity.",
                        "Always gamble responsibly and within set bankrolls."
                    ].map((item, idx) => (
                        <div key={idx} className="flex flex-col gap-2 p-4 rounded-xl bg-black/40 border border-white/5 text-center items-center justify-center">
                            <div className="w-8 h-8 rounded-full bg-yellow-500/10 flex items-center justify-center border border-yellow-500/20">
                                <span className="text-xs font-black text-yellow-500">{idx + 1}</span>
                            </div>
                            <span className="text-zinc-300 font-medium text-sm leading-relaxed">{item}</span>
                        </div>
                    ))}
                </div>
            </section>

            <section className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8">
                <div className="flex items-center gap-3 mb-6">
                    <Copyright className="w-6 h-6 text-emerald-500" />
                    <h2 className="text-xl md:text-2xl font-black text-white tracking-tight uppercase italic">4. Intellectual Property</h2>
                </div>
                <p className="text-zinc-400 leading-relaxed font-medium">
                    The technology, algorithms, brand, code, and design architecture of Sharp Picks AI are the exclusive property of Sharp Picks Analytics. Users are granted a limited, localized, non-exclusive license to use the service for personal, non-commercial use only.
                </p>
            </section>

            <section className="bg-zinc-900/40 border border-white/5 rounded-3xl p-6 md:p-8">
                <div className="flex items-center gap-3 mb-6">
                    <Scale className="w-6 h-6 text-blue-500" />
                    <h2 className="text-xl md:text-2xl font-black text-white tracking-tight uppercase italic">5. Limitation of Liability</h2>
                </div>
                <p className="text-zinc-400 leading-relaxed font-medium">
                    To the absolute maximum extent permitted by law, Sharp Picks AI shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service, including but not limited to catastrophic financial losses or ruin from sports wagering. 
                </p>
            </section>
        </LegalPageLayout>
    )
}
