import { LegalPageLayout } from "@/components/landing/LegalPageLayout"

export default function TermsPage() {
    return (
        <LegalPageLayout
            title="Terms of Service"
            subtitle="Last updated: February 15, 2024"
        >
            <section>
                <h2>1. Acceptance of Terms</h2>
                <p>
                    By accessing and using ProfitPicks AI (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service. Our platform provides sports analytics and data processing for entertainment and informational purposes only.
                </p>
            </section>

            <section>
                <h2>2. Description of Service</h2>
                <p>
                    ProfitPicks AI provides advanced sports data analytics, predictive modeling, and +EV (Expected Value) identification using proprietary AI algorithms. We do not facilitate sports wagering, nor are we a licensed gambling operator.
                </p>
            </section>

            <section>
                <h2>3. Use for Entertainment Only</h2>
                <p>
                    <strong>IMPORTANT:</strong> All data, predictions, and "picks" generated by ProfitPicks AI are for entertainment purposes only. Sports betting involves significant risk. ProfitPicks AI does not guarantee any financial outcome and is not responsible for any losses incurred as a result of using our analytical tools.
                </p>
                <ul>
                    <li>Past performance does not guarantee future results.</li>
                    <li>The user assumes all risk for any betting activity.</li>
                    <li>Always gamble responsibly.</li>
                </ul>
            </section>

            <section>
                <h2>4. Intellectual Property</h2>
                <p>
                    The technology, algorithms, brand, and design of ProfitPicks AI are the exclusive property of ProfitPicks Analytics. Users are granted a limited, non-exclusive license to use the service for personal, non-commercial use.
                </p>
            </section>

            <section>
                <h2>5. Limitation of Liability</h2>
                <p>
                    To the maximum extent permitted by law, ProfitPicks AI shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service, including but not limited to financial losses from sports wagering.
                </p>
            </section>
        </LegalPageLayout>
    )
}
